spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: teste
      secret-key: teste
    end-point:
      uri: http://localhost:4566/000000000000/queue-send-example-local-stack
    queue:
      name: queue-send-example-local-stack